---
apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  containers:
  - args:
    - --context=git://github.com/kjenney/my-rest-service.git
    - --destination=docker-registry.registry.svc.cluster.local:5000/test/app:1.0
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    name: kaniko
  dnsPolicy: ClusterFirst
  restartPolicy: Never
