apiVersion: v1
kind: Namespace
metadata:
  name: my-rest-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask
  name: my-rest-service
  namespace: my-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask
    spec:
      containers:
      - image: localhost:5000/test/my-rest-service:v1
        name: flask
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-rest-service
  namespace: my-rest-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000